version: "3.9"

services:
  # openhab:
  #   image: "openhab/openhab:3.3.0"
  #   restart: always

  #   ports:
  #     - "8080:8080"
  #     - "8443:8443"
  #   volumes:
  #     - "/etc/localtime:/etc/localtime:ro"
  #     # - "/etc/timezone:/etc/timezone:ro"
  #     - "./data/openhab/addons:/openhab/addons"
  #     - "./data/openhab/config:/openhab/conf"
  #     - "./data/openhab/data:/openhab/userdata"
  #     - "/dev/cu.usbserial-AH01HYRV:/dev/cu.usbserial-AH01HYRV"
  #   environment:
  #     OPENHAB_HTTP_PORT: "8080"
  #     OPENHAB_HTTPS_PORT: "8443"
  #     EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/Vienna"

  mosquitto:
    image: "eclipse-mosquitto"
    restart: always

    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - "./data/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf"
      - "./data/mosquitto/data:/mosquitto/data"
      - "./data/mosquitto/log:/mosquitto/log/"
